config/routes.rb
Rails.application.routes.draw do
  resources :lakesides
  resources :riversides
  #get 'bookings/index'
  #get 'bookings/edit'
  #get 'bookings/show'
  resources :bookings do
    collection do
      post :import
      get :autocomplete
    end
  end

  resources :customers do
    collection do
      get '/customer_lists', to: 'customers#customer_lists', as: :user
    end
  end

  devise_for :users
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lakeside.rb
class Lakeside < ApplicationRecord
	belongs_to :user
	has_many :bookings
	has_many :customers, through: :bookings

end

app/controllers/lakesides_controller.rb
class LakesidesController < ApplicationController
  before_action :set_lakeside, only: [:show, :edit, :update, :destroy]

  # GET /lakesides
  # GET /lakesides.json
  def index
    @lakesides = Lakeside.all
    #@bookings = Booking.all
  end

  # GET /lakesides/1
  # GET /lakesides/1.json
  def show
  end

  # GET /lakesides/new
  def new
    @lakeside = Lakeside.new
  end

  # GET /lakesides/1/edit
  def edit
  end

  # POST /lakesides
  # POST /lakesides.json
  def create
    @lakeside = Lakeside.new(lakeside_params)

    respond_to do |format|
      if @lakeside.save
        format.html { redirect_to @lakeside, notice: 'Lakeside was successfully created.' }
        format.json { render :show, status: :created, location: @lakeside }
      else
        format.html { render :new }
        format.json { render json: @lakeside.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lakesides/1
  # PATCH/PUT /lakesides/1.json
  def update
    respond_to do |format|
      if @lakeside.update(lakeside_params)
        format.html { redirect_to @lakeside, notice: 'Lakeside was successfully updated.' }
        format.json { render :show, status: :ok, location: @lakeside }
      else
        format.html { render :edit }
        format.json { render json: @lakeside.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lakesides/1
  # DELETE /lakesides/1.json
  def destroy
    @lakeside.destroy
    respond_to do |format|
      format.html { redirect_to lakesides_url, notice: 'Lakeside was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lakeside
      @lakeside = Lakeside.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lakeside_params
      params.require(:lakeside).permit(:organization, :packet, :start_time, :end_time, :status)
    end
end

app/helpers/lakesides_helper.rb
module LakesidesHelper
end

app/views/lakesides/_form.html.erb
<%= form_for(lakeside) do |f| %>
  <% if lakeside.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lakeside.errors.count, "error") %> prohibited this lakeside from being saved:</h2>

      <ul>
      <% lakeside.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization %>
    <%= f.text_field :organization %>
  </div>

  <div class="field">
    <%= f.label :packet %>
    <%= f.text_field :packet %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lakesides/edit.html.erb
<h1>Editing Lakeside</h1>

<%= render 'form', lakeside: @lakeside %>

<%= link_to 'Show', @lakeside %> |
<%= link_to 'Back', lakesides_path %>

app/views/lakesides/index.html.erb
<h1>Lakesides</h1>

<%= form_tag(bookings_path, :method => "get", class: "form-inline") do %>
    <div class="input-group input-group-lg">
      <% if params[:query].present? %>
       <div class="input-group-btn">
         <%= link_to "clear", bookings_path, class: "btn btn-default" %>
       </div>
      <% end %>
      <%= text_field_tag :query, params[:query], class: "form-control", id: "booking_search", autocomplete: "off" %>
      <div class="input-group-btn">
          <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

<div id="calendar" style="max-width: 60%;"></div>

<h2>Lakeside</h2>
<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Packet</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lakesides.each do |lakeside| %>
      <tr>
        <td><%= lakeside.organization %></td>
        <td><%= lakeside.packet %></td>
        <td><%= lakeside.start_time %></td>
        <td><%= lakeside.end_time %></td>
        <td><%= lakeside.status %></td>
        <td><%= link_to 'Show', lakeside %></td>
        <td><%= link_to 'Edit', edit_lakeside_path(lakeside) %></td>
        <td><%= link_to 'Destroy', lakeside , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Lakeside", new_lakeside_path %>

app/views/lakesides/new.html.erb
<h1>New Lakeside</h1>

<%= render 'form', lakeside: @lakeside %>

<%= link_to 'Back', lakesides_path %>

app/views/lakesides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization:</strong>
  <%= @lakeside.organization %>
</p>

<p>
  <strong>Packet:</strong>
  <%= @lakeside.packet %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @lakeside.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @lakeside.end_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lakeside.status %>
</p>

<%= link_to 'Edit', edit_lakeside_path(@lakeside) %> |
<%= link_to 'Back', lakesides_path %>