config/routes.rb
Rails.application.routes.draw do
  resources :lakesides
  resources :riversides
  #get 'bookings/index'
  #get 'bookings/edit'
  #get 'bookings/show'
  resources :bookings do
    collection do
      post :import
      get :autocomplete
    end
  end

  resources :customers do
    collection do
      get '/customer_lists', to: 'customers#customer_lists', as: :user
    end
  end

  devise_for :users
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/riverside.rb
class Riverside < ApplicationRecord
	has_many :bookings
	has_many :customers, through: :bookings
end

app/controllers/riversides_controller.rb
class RiversidesController < ApplicationController
  before_action :set_riverside, only: [:show, :edit, :update, :destroy]

  # GET /riversides
  # GET /riversides.json
  def index
    @riversides = Riverside.all
  end

  # GET /riversides/1
  # GET /riversides/1.json
  def show
  end

  # GET /riversides/new
  def new
    @riverside = Riverside.new
  end

  # GET /riversides/1/edit
  def edit
  end

  # POST /riversides
  # POST /riversides.json
  def create
    @riverside = Riverside.new(riverside_params)

    respond_to do |format|
      if @riverside.save
        format.html { redirect_to @riverside, notice: 'Riverside was successfully created.' }
        format.json { render :show, status: :created, location: @riverside }
      else
        format.html { render :new }
        format.json { render json: @riverside.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riversides/1
  # PATCH/PUT /riversides/1.json
  def update
    respond_to do |format|
      if @riverside.update(riverside_params)
        format.html { redirect_to @riverside, notice: 'Riverside was successfully updated.' }
        format.json { render :show, status: :ok, location: @riverside }
      else
        format.html { render :edit }
        format.json { render json: @riverside.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riversides/1
  # DELETE /riversides/1.json
  def destroy
    @riverside.destroy
    respond_to do |format|
      format.html { redirect_to riversides_url, notice: 'Riverside was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_riverside
      @riverside = Riverside.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def riverside_params
      params.require(:riverside).permit(:organization, :start_time, :end_time, :status)
    end
end

app/helpers/riversides_helper.rb
module RiversidesHelper
end

app/views/riversides/_form.html.erb
<%= form_for(riverside) do |f| %>
  <% if riverside.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(riverside.errors.count, "error") %> prohibited this riverside from being saved:</h2>

      <ul>
      <% riverside.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>

  <div class="field">
    <%= f.label :packet %>
    <%= f.text_field :packet %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/riversides/edit.html.erb
<h1>Editing Riverside</h1>

<%= render 'form', riverside: @riverside %>

<%= link_to 'Show', @riverside %> |
<%= link_to 'Back', riversides_path %>

app/views/riversides/index.html.erb
<h1>Riversides</h1>

<%= month_calendar events: @riversides do |date, riversides| %>
  <%= date %>

  <% riversides.each do |riverside| %>
    <div>
      <%= link_to riverside.organization, riverside %>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riversides.each do |riverside| %>
      <tr>
        <td><%= riverside.organization %></td>
        <td><%= riverside.start_time %></td>
        <td><%= riverside.end_time %></td>
        <td><%= riverside.status %></td>
        <td><%= link_to 'Show', riverside %></td>
        <td><%= link_to 'Edit', edit_riverside_path(riverside) %></td>
        <td><%= link_to 'Destroy', riverside, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Riverside', new_riverside_path %>

app/views/riversides/new.html.erb
<h1>New Riverside</h1>

<%= render 'form', riverside: @riverside %>

<%= link_to 'Back', riversides_path %>

app/views/riversides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit:</strong>
  <%= @riverside.unit %>
</p>

<p>
  <strong>Packet:</strong>
  <%= @riverside.packet %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @riverside.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @riverside.end_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @riverside.status %>
</p>

<%= link_to 'Edit', edit_riverside_path(@riverside) %> |
<%= link_to 'Back', riversides_path %>