config/routes.rb
Rails.application.routes.draw do
  resources :lakesides
  resources :riversides
  #get 'bookings/index'
  #get 'bookings/edit'
  #get 'bookings/show'
  resources :bookings do
    collection do
      post :import
      get :autocomplete
    end
  end

  resources :customers do
    collection do
      get '/customer_lists', to: 'customers#customer_lists', as: :user
    end
  end

  devise_for :users
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://citraalam.id/">Citra Alam App</a>
    by <a href="http://awakeningsuite.myshopify.com">Awakening Suite Suite</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://citraalam.id/">Citra Alam</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Citra Alam", root_path, id: "logo", class: 'navbar-brand' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Add Customer", new_customer_path %></li>
        <li><%= link_to "Daftar Nama", user_customers_path %></li>        
        <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%# full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>


  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p id="notice" class="notice"><%= notice %></p>
      <p id="notice" class="alert"><%= alert %></p>

      <div class="notice">
        <% if user_signed_in? %>
          <% case current_user.role %>
          <% when 'user' %>
            <h3>Welcome</h3>
          <% when 'marketing' %>
            <h3>Welcome, <%= current_user.email %></h3>
          <% when 'unit' %>
            <h3>Welcome, <%= current_user.email %></h3>
          <% when 'admin' %>
            <h3>Welcome, Administrator</h3>
          <% end %>
        <% end %>
      </div>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>